package com.kingfish.show.mybatis.model;

import java.util.Date;

public class Product {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_id
     *
     * @mbg.generated
     */
    private Long productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.gmt_modify
     *
     * @mbg.generated
     */
    private Date gmtModify;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.is_p4p
     *
     * @mbg.generated
     */
    private Boolean isP4p;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.url_p4p
     *
     * @mbg.generated
     */
    private String urlP4p;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.cate_id
     *
     * @mbg.generated
     */
    private Long cateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.view_sales
     *
     * @mbg.generated
     */
    private String viewSales;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.sale_id
     *
     * @mbg.generated
     */
    private Long saleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.l1_category
     *
     * @mbg.generated
     */
    private Long l1Category;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_id
     *
     * @return the value of product.product_id
     *
     * @mbg.generated
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_id
     *
     * @param productId the value for product.product_id
     *
     * @mbg.generated
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.gmt_create
     *
     * @return the value of product.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.gmt_create
     *
     * @param gmtCreate the value for product.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.gmt_modify
     *
     * @return the value of product.gmt_modify
     *
     * @mbg.generated
     */
    public Date getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.gmt_modify
     *
     * @param gmtModify the value for product.gmt_modify
     *
     * @mbg.generated
     */
    public void setGmtModify(Date gmtModify) {
        this.gmtModify = gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.url
     *
     * @return the value of product.url
     *
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.url
     *
     * @param url the value for product.url
     *
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.is_p4p
     *
     * @return the value of product.is_p4p
     *
     * @mbg.generated
     */
    public Boolean getIsP4p() {
        return isP4p;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.is_p4p
     *
     * @param isP4p the value for product.is_p4p
     *
     * @mbg.generated
     */
    public void setIsP4p(Boolean isP4p) {
        this.isP4p = isP4p;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.url_p4p
     *
     * @return the value of product.url_p4p
     *
     * @mbg.generated
     */
    public String getUrlP4p() {
        return urlP4p;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.url_p4p
     *
     * @param urlP4p the value for product.url_p4p
     *
     * @mbg.generated
     */
    public void setUrlP4p(String urlP4p) {
        this.urlP4p = urlP4p == null ? null : urlP4p.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.cate_id
     *
     * @return the value of product.cate_id
     *
     * @mbg.generated
     */
    public Long getCateId() {
        return cateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.cate_id
     *
     * @param cateId the value for product.cate_id
     *
     * @mbg.generated
     */
    public void setCateId(Long cateId) {
        this.cateId = cateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.view_sales
     *
     * @return the value of product.view_sales
     *
     * @mbg.generated
     */
    public String getViewSales() {
        return viewSales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.view_sales
     *
     * @param viewSales the value for product.view_sales
     *
     * @mbg.generated
     */
    public void setViewSales(String viewSales) {
        this.viewSales = viewSales == null ? null : viewSales.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.sale_id
     *
     * @return the value of product.sale_id
     *
     * @mbg.generated
     */
    public Long getSaleId() {
        return saleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.sale_id
     *
     * @param saleId the value for product.sale_id
     *
     * @mbg.generated
     */
    public void setSaleId(Long saleId) {
        this.saleId = saleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.l1_category
     *
     * @return the value of product.l1_category
     *
     * @mbg.generated
     */
    public Long getL1Category() {
        return l1Category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.l1_category
     *
     * @param l1Category the value for product.l1_category
     *
     * @mbg.generated
     */
    public void setL1Category(Long l1Category) {
        this.l1Category = l1Category;
    }
}