package com.kingfish.show.mybatis.model;

import java.util.Date;

public class Show {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column show.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column show.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column show.gmt_modify
     *
     * @mbg.generated
     */
    private Date gmtModify;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column show.truth
     *
     * @mbg.generated
     */
    private Double truth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column show.praise
     *
     * @mbg.generated
     */
    private Integer praise;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column show.product_id
     *
     * @mbg.generated
     */
    private Long productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column show.source
     *
     * @mbg.generated
     */
    private Byte source;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column show.pics
     *
     * @mbg.generated
     */
    private String pics;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column show.id
     *
     * @return the value of show.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column show.id
     *
     * @param id the value for show.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column show.gmt_create
     *
     * @return the value of show.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column show.gmt_create
     *
     * @param gmtCreate the value for show.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column show.gmt_modify
     *
     * @return the value of show.gmt_modify
     *
     * @mbg.generated
     */
    public Date getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column show.gmt_modify
     *
     * @param gmtModify the value for show.gmt_modify
     *
     * @mbg.generated
     */
    public void setGmtModify(Date gmtModify) {
        this.gmtModify = gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column show.truth
     *
     * @return the value of show.truth
     *
     * @mbg.generated
     */
    public Double getTruth() {
        return truth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column show.truth
     *
     * @param truth the value for show.truth
     *
     * @mbg.generated
     */
    public void setTruth(Double truth) {
        this.truth = truth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column show.praise
     *
     * @return the value of show.praise
     *
     * @mbg.generated
     */
    public Integer getPraise() {
        return praise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column show.praise
     *
     * @param praise the value for show.praise
     *
     * @mbg.generated
     */
    public void setPraise(Integer praise) {
        this.praise = praise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column show.product_id
     *
     * @return the value of show.product_id
     *
     * @mbg.generated
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column show.product_id
     *
     * @param productId the value for show.product_id
     *
     * @mbg.generated
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column show.source
     *
     * @return the value of show.source
     *
     * @mbg.generated
     */
    public Byte getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column show.source
     *
     * @param source the value for show.source
     *
     * @mbg.generated
     */
    public void setSource(Byte source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column show.pics
     *
     * @return the value of show.pics
     *
     * @mbg.generated
     */
    public String getPics() {
        return pics;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column show.pics
     *
     * @param pics the value for show.pics
     *
     * @mbg.generated
     */
    public void setPics(String pics) {
        this.pics = pics == null ? null : pics.trim();
    }
}